const PRICE_TOTAL_UPDATE = "PRICE_TOTAL_UPDATE";
const PRICE_CAR_UPDATE = "PRICE_CAR_UPDATE";
const PRICE_SEATS_UPDATE = "PRICE_SEATS_UPDATE";
const DAYS_UPDATE = "PRICE_DAYS_UPDATE";
const GPS_SELECTED = "GPS_SELECTED";
const FORM_ACTIVE = "FORM_ACTIVE";
const CONFIRMATION = "CONFIRMATION";
const OPEN_HEADER_FORM = "OPEN_HEADER_FORM";
const OPEN_MODAL_CONFERMATION = "OPEN_MODAL_CONFERMATION";
const RESET = "RESET";
const SET_FULL_NAME = "SET_FULL_NAME";
const SET_DATE_START = "SET_DATE_START";
const SET_DATE_END = "SET_DATE_END";
const SET_MOBILE = "SET_MOBILE";
const SET_ADRESS = "SET_ADRESS";
const SET_CAR_NAME = "SET_CAR_NAME";
const SET_EMAIL = "SET_EMAIL"
const SET_AGENCE = "SET_AGENCE"
const SET_CARD_RESEVARTION = "SET_CARD_RESEVARTION"

export default {
  PRICE_TOTAL_UPDATE,
  PRICE_CAR_UPDATE,
  PRICE_SEATS_UPDATE,
  DAYS_UPDATE,
  GPS_SELECTED,
  FORM_ACTIVE,
  CONFIRMATION,
  OPEN_HEADER_FORM,
  OPEN_MODAL_CONFERMATION,
  RESET,
  SET_FULL_NAME,
  SET_DATE_START,
  SET_DATE_END,
  SET_MOBILE,
  SET_ADRESS,
  SET_CAR_NAME,
  SET_EMAIL,
  SET_AGENCE,
  SET_CAR_NAME,
  SET_CARD_RESEVARTION
};
